'use client';

import React from 'react';
import { LegalLayout } from '@/src/components/LegalLayout';

export default function TermsOfServicePage() {
  return (
    <LegalLayout
      title="Master Terms of Service & Software License Agreement"
      subtitle="The legally binding contract governing the subscription, installation, operation, and fair use of the AgroFlow Agribusiness Operating System across licensed agrovets and enterprises."
      effectiveDate="September 6, 2026"
      version="v2026.2"
      activeDoc="terms"
    >
      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          1. Preamble &amp; Acceptance of Agreement
        </h2>
        <p>
          This Master Terms of Service Agreement (the <strong>&quot;Agreement&quot;</strong>) is entered into between <strong>AgroFlow Technologies Kenya Limited</strong> (<strong>&quot;AgroFlow&quot;</strong>, <strong>&quot;Licensor&quot;</strong>, or <strong>&quot;we&quot;</strong>), a legal entity incorporated under the Companies Act of Kenya, and the licensed agro-enterprise, agrovet cooperative, or individual merchant operating the software (the <strong>&quot;Licensee&quot;</strong>, <strong>&quot;Merchant&quot;</strong>, or <strong>&quot;you&quot;</strong>).
        </p>
        <p>
          By accessing, subscribing to, configuring, or running the AgroFlow platform across store point-of-sale (POS) terminals, back-office dashboards, or mobile devices, you acknowledge that you have read, understood, and agreed to be legally bound by these terms. If you are accepting on behalf of an enterprise or cooperative society, you warrant that you possess the requisite authority to bind such entity.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          2. Commercial License Grant &amp; Permitted Scope
        </h2>
        <p>
          Subject to the terms and timely payment of applicable subscription or licensing fees, AgroFlow grants the Licensee a non-exclusive, non-transferable, revocable commercial license to deploy and operate the AgroFlow software solely for:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Managing point-of-sale retail transactions, inventory dispensaries, and batch FEFO tracking.</li>
          <li>Maintaining farmer customer registries, KYC profiles, and revolving credit books.</li>
          <li>Recording shift cash drawer tallies, Z-report daily closes, and supplier goods received notes (GRN).</li>
          <li>Facilitating integrated telecommunications (SMS payment reminders) and Safaricom M-Pesa STK push checkouts.</li>
        </ul>
        <p className="bg-amber-50 p-3 rounded-lg border border-amber-200 text-amber-950 text-xs">
          <strong>Fair Restriction:</strong> The Licensee shall not reverse-engineer, decompile, redistribute, or lease the core proprietary engine to un-affiliated third-party software brokers.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          3. Absolute Protection of Licensee Data Ownership
        </h2>
        <p>
          AgroFlow recognizes that an agrovet&apos;s customer ledger, supplier wholesale pricing, and transaction history constitute sensitive proprietary commercial assets. We guarantee the following fair covenants:
        </p>
        <div className="bg-emerald-50/70 p-4 rounded-xl border border-emerald-200 space-y-2 text-xs text-emerald-950">
          <div className="font-bold flex items-center gap-1.5 text-emerald-900">
            <span className="material-symbols-outlined text-sm">lock</span>
            Covenant of Data Sovereignty &amp; Non-Expropriation
          </div>
          <p>
            (a) <strong>100% Merchant Ownership:</strong> You retain exclusive ownership of all farmer contact data, credit balances, product pricing margins, and store financial audits uploaded to or generated by AgroFlow.
          </p>
          <p>
            (b) <strong>Zero Commercial Monetization of Store Records:</strong> AgroFlow will never sell, rent, or lease your store transactions or farmer contacts to agrochemical manufacturers, marketing agencies, or competing retail networks.
          </p>
          <p>
            (c) <strong>On-Demand Export Rights:</strong> The Licensee holds the unrestricted right at any time to export their complete database (products, ledger entries, transactions) in open CSV / JSON format.
          </p>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          4. Service Availability, Maintenance &amp; Offline Resiliency
        </h2>
        <p>
          AgroFlow provides commercial-grade software engineered with offline-tolerant capabilities to ensure that remote Kenyan agrovets in rural blocks can continue recording counter sales during telecommunication outages.
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Service Level Target:</strong> AgroFlow endeavors to maintain 99.5% availability for centralized cloud synchronization and SMS relay services.</li>
          <li><strong>Scheduled Maintenance:</strong> Maintenance requiring cloud downtime will be conducted during off-peak hours (between 11:00 PM and 4:00 AM EAT) with a minimum of 48 hours prior notification via dashboard broadcast.</li>
          <li><strong>Disaster Recovery:</strong> Nightly encrypted incremental backups are maintained. In the event of catastrophic local terminal failure, AgroFlow technical support will assist in database restoration within 4 business hours.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          5. User Authentication, PIN Security &amp; Role Integrity
        </h2>
        <p>
          The platform enforces role-based access control (Store Manager vs. Terminal Cashier) and Manager PIN authorizations for shift locking and drawer reconciliation:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Licensee Duty of Care:</strong> The Licensee is solely responsible for maintaining the confidentiality of administrative credentials and Manager PINs.</li>
          <li><strong>Audit Trail Immutability:</strong> All shift lockings, price overrides, and cash drawer reconciliations are indelibly logged with cashier timestamps. AgroFlow will not tamper with or alter verified transaction logs.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          6. Fees, Billing Transparency &amp; Non-Predatory Terms
        </h2>
        <p>
          AgroFlow operates under clear, transparent subscription pricing without hidden runtime levies:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Subscription fees are billed monthly or annually in Kenya Shillings (KES) inclusive of applicable statutory taxes (VAT).</li>
          <li><strong>No Arbitrary Hikes:</strong> Any subscription fee revisions require a minimum of sixty (60) days advance written notice.</li>
          <li><strong>Grace Period on Renewal:</strong> In the event of an expired subscription, a seven (7) day grace period applies during which read and POS sale functions remain operational to prevent disrupting retail farm operations.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          7. Warranties, Limitation of Liability &amp; Risk Allocation
        </h2>
        <p>
          (a) <strong>Software Warranty:</strong> AgroFlow warrants that the software will perform substantially in accordance with its published user manuals under normal operating conditions.
        </p>
        <p>
          (b) <strong>Limitation of Consequential Damages:</strong> Neither party shall be liable to the other for indirect, special, incidental, or consequential damages (including lost crop harvest profits or business interruption) arising out of the use or inability to use the platform.
        </p>
        <p>
          (c) <strong>Aggregate Liability Cap:</strong> AgroFlow&apos;s total aggregate commercial liability under this Agreement shall not exceed the total subscription fees paid by the Licensee in the twelve (12) months preceding the incident giving rise to the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          8. Non-Hostile Termination &amp; 30-Day Transition Guarantee
        </h2>
        <p>
          Either party may terminate this Agreement without penalty upon thirty (30) days written notice.
        </p>
        <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 text-xs space-y-1.5">
          <div className="font-bold text-gray-800">30-Day Transition Guarantee:</div>
          <p>
            Upon termination, AgroFlow will provide the Licensee with thirty (30) consecutive calendar days of read-only access to download all farmer accounts, transaction ledgers, and inventory histories. Under no circumstances will AgroFlow hold Licensee customer or financial data hostage.
          </p>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="font-playfair font-bold text-base sm:text-lg text-[#003b1b] border-b pb-1.5">
          9. Governing Law &amp; Dispute Resolution
        </h2>
        <p>
          This Agreement is governed by and construed in accordance with the substantive laws of the <strong>Republic of Kenya</strong>.
        </p>
        <p>
          In the event of any commercial disagreement or claim, the parties shall first attempt to resolve the dispute amicably through good-faith executive negotiations within twenty-one (21) days. If unresolved, the dispute shall be referred to and finally resolved by arbitration administered by the <strong>Nairobi Centre for International Arbitration (NCIA)</strong> in accordance with the NCIA Arbitration Rules. The seat of arbitration shall be Nairobi, Kenya, and proceedings shall be conducted in English.
        </p>
      </section>
    </LegalLayout>
  );
}
